spring.datasource.url=jdbc:postgresql://dpg-d9jfied8nd3s73bavk20-a/ariza_db
spring.datasource.username=ariza_db_user
spring.datasource.password=giOhbLraDroakUQCciR56hP3EZRhNcIE
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Hibernate'in dialect ve URL hatasını tamamen ortadan kaldıran kesin ayarlar:
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.jakarta.persistence.jdbc.url=jdbc:postgresql://dpg-d9jfied8nd3s73bavk20-a/ariza_db
spring.jpa.properties.jakarta.persistence.jdbc.user=ariza_db_user
spring.jpa.properties.jakarta.persistence.jdbc.password=giOhbLraDroakUQCciR56hP3EZRhNcIE
spring.jpa.properties.jakarta.persistence.jdbc.driver=org.postgresql.Driver

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true